### ISSUE TITLE
MyWarp crashed when value bundles are not properly configured

### ISSUE THREAD

**Issue by TheE** [TheE/MyWarp#102]
When a user messes up the formatting of any value bundle (e.g. by missing a required value), MyWarp crashes with an NPE. It would be better if an error was displayed (perhaps ignore the malformed value bundle and continue?).

**Comment by TheE** [comment]
The crash can be reproduced with the following configuration:
````YAML
limits:
  enabled: true
  defaultLimit:
    totalLimit: 15
    publicLimit: 5
    privateLimit: 10
  configuredLimits:
    memberplus:
      totalLimit: 1
      publicLimit: 1
      privateLimit: 1
    affectedWorlds:
    - fort-stoneguard
````
Specifically, `affectedWords` is read as a dedicated limit bundle, but the constructor of LimitBundle throws an NPE because the corresponding ConfigurationSection is `null`.

Perhaps `BukkitSettings` could do additional checks before initializing the bundle?
