### ISSUE TITLE
Limit doesn't update

### ISSUE THREAD

**Issue by natkemon** [TheE/MyWarp#111]
Hello.

Currently having an issue with limit configuration. This is the limit section of the config: http://pastebin.com/pCWUZL5X

Problem is that the defaultLimit doesn't update to 0 but continues to stay at 5 public and 10 private warps. 

What have i done wrong?

**Comment by TheE** [comment]
I cannot reproduce this. Could you test again with the latest devBuild and post the output of `/warp assets` for a player that should have the default limit?

Beides you should remove `affectedWorlds` from the default limit as it is always ignored (the default limit is always global). If you only have two worlds (`Skybros` and `Spawn`) I would recommend to also remove `affectedWorlds` from all other limits as limits without it are always global.

**Comment by natkemon** [comment]
Currently using the latest devBuild. Running version 1.9.4
My user Ghostman132 assets are as displayed: http://prntscr.com/c0584y

Currently have more than 2 worlds (skybros and spawn). So i should leave it as it is i assume.

**Comment by TheE** [comment]
This is definitely not the latest devBuild (I changed the formatting of `warp assets` some time ago and this looks like the old one). Please try [this](https://thee140.ci.cloudbees.com/job/mywarp3_bukkit/123/) one.

**Comment by natkemon** [comment]
Getting an error upon typing a command like /warp list
http://pastebin.com/wJAaj2Du

**Comment by TheE** [comment]
My bad - that is already fixed in code but since currently the repository of Vault is offline, automatic builds do not work.

Please try the build before the one I linked above: https://thee140.ci.cloudbees.com/job/mywarp3_bukkit/122/

**Comment by natkemon** [comment]
The above build works. Tested and some parts work. THe problematic parts is warps for obsidian and skybro are staying on a limit of 2 rather than 3 and 4 respecitvely.

**Comment by TheE** [comment]
Yes, the limits `obsidian` and `skybro` are overwritten by `gold`.

Limit permissions are resolved in lexicographical order. If a user happens to have permission for two limits, the lexicographical first applies. This means that you cannot name the limits like you want to, but must name them in a way that takes the lexicographical ordering into account, e.g. like so:

````YAML
  configuredLimits:
    j_ sand:
      totalLimit: 1
      publicLimit: 1
      privateLimit: 0
      affectedWorlds:
      - skybros
      - Spawn
    g_ gold:
      totalLimit: 2
      publicLimit: 2
      privateLimit: 0
      affectedWorlds:
      - skybros
      - Spawn
    d_obsidian:
      totalLimit: 3
      publicLimit: 3
      privateLimit: 0
      affectedWorlds:
      - skybros
      - Spawn
    a_skybro:
      totalLimit: 4
      publicLimit: 4
      privateLimit: 0
      affectedWorlds:
      - skybros
      - Spawn
````
