### ISSUE TITLE
MyWarp v2.6.5 - limits

### ISSUE THREAD

**Issue by kirich1368** [TheE/MyWarp#140]
Please tell me how to issue limits in permissionsex ?

![3](https://cloud.githubusercontent.com/assets/18468664/24581549/4c84082e-1726-11e7-8b70-d33e749a28e8.png)

**Comment by q220** [comment]
It seems there's a problem with identation starting at grand, it is on the same level as configured-limits while it should be within.

**Comment by TheE** [comment]
q220 is correct, the intention is wrong.

Also you might want to check [this](https://github.com/TheE/MyWarp/wiki/Creation-Limits/f85264e9a9ffc36e6cbe83ac9ae7e971fb26243f) page which contains information about limits in 2.6.5.

**Comment by kirich1368** [comment]
I enter the command: **/warp pcreate 1**, writes: 
![11](https://cloud.githubusercontent.com/assets/18468664/24710397/ad5c1f9a-1a25-11e7-96c2-f7fa5a50a08c.png)

Group vip have the right **mywarp.limit.vip**

config:

https://pastebin.com/bkyKPUJR

**Comment by TheE** [comment]
The indentation is still wrong, it needs to look like this:

````YAML
limits:
  enabled: true
  configured-limits:
    default:
      totalLimit: 0
      publicLimit: 0
      privateLimit: 0
    grand:
      totalLimit: 5
      publicLimit: 2
      privateLimit: 3
    premium:
      totalLimit: 3
      publicLimit: 1
      privateLimit: 2
    vip:
      totalLimit: 1
      publicLimit: 0
      privateLimit: 1
````

(This was one of the reasons why I changed the formatting in MyWarp 3: It is hard to tell if the there are enough spaces infant of each limit declaration.)
