### ISSUE TITLE
Groups Not Working. (Again)

### ISSUE THREAD

**Issue by DutchUser** [TheE/MyWarp#27]
Hey, I try with my vriend for teh limits but they are not working also if its alfabtich etc,
groups
MyWarp
limits:
  enabled: true
  configured-limits:
    default:
      totalLimit: 0
      publicLimit: 0
      privateLimit: 0
    user:
      totalLimit: 0
      publicLimit: 0
      privateLimit: 0
      affectedWorlds:
      - world
    U_Noob:
      totalLimit: 0
      publicLimit: 0
      privateLimit: 0
    H_Noob+:
      totalLimit: 10
      PublicLimit: 0
      privateLimit: 10
    B_Premium:
      totalLimit: 27
      publicLimit: 2
      privateLimit: 25
    D_Moderator:
      totalLimit: 28
      publicLimit: 3
      privateLimit: 25
    E_Moderator++:
      totalLimit: 28
      publicLimit: 3
      privateLimit: 25
    Admin:
      totalLimit: 75
      publicLimit: 25
      privateLimit: 50
PEX: 
  User:
    permissions:
    - mywarp.warp.basic.*
    - mywarp.warp.soc.*
    - mywarp.limit.U_Noob
    options:
      default: true
  Master:
    inheritance:
    - User
    permissions:
    - mywarp.limit.H_Noob+
  Captain:
    inheritance:
    - Master
    permissions:
    - mywarp.limit.B_Premium
    worlds:
      world_nether:
        permissions:
        - -essentials.top
      TheNether2:
        permissions:
        - -essentials.top
  Moderator:
    permissions:
    - mywarp.warp.basic.*
    - mywarp.warp.soc.*
    - mywarp.limit.D_Moderator

So why hes not working?.

**Comment by TheE** [comment]
A general notice: If you post code here on GitHub, make sure to either post them as [fenced code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) or on an external side such as [Pastbin](http://pastebin.com/) so that the formatting is preserved.

What exactly is not working and what version of MyWarp are you using? MyWarp 2.6.5 or MyWarp 3-SNAPSHOT which is currently in development?

**Comment by DutchUser** [comment]
I have : MyWarp v2.6.5

**Comment by TheE** [comment]
Which limit is not working? Which permission group does the user you are testing with have and which of the limits should apply to him? And what does `/warp assets` for that user say?

If your configuration looks like this I cannot spot a configuration error:
````YAML
limits:
  enabled: true
  configured-limits:
    default:
      totalLimit: 0
      publicLimit: 0
      privateLimit: 0
    user:
      totalLimit: 0
      publicLimit: 0
      privateLimit: 0
      affectedWorlds:
      - world
    U_Noob:
      totalLimit: 0
      publicLimit: 0
      privateLimit: 0
    H_Noob+:
      totalLimit: 10
      PublicLimit: 0
      privateLimit: 10
    B_Premium:
      totalLimit: 27
      publicLimit: 2
      privateLimit: 25
    D_Moderator:
      totalLimit: 28
      publicLimit: 3
      privateLimit: 25
    E_Moderator++:
      totalLimit: 28
      publicLimit: 3
      privateLimit: 25
    Admin:
      totalLimit: 75
      publicLimit: 25
      privateLimit: 50
````
