### ISSUE TITLE
An strange thing

### ISSUE THREAD

**Issue by DutchUser** [TheE/MyWarp#67]
Hello. i got an strange limit issue. When i have OP i not got the higest limit. No i got also not the lowst but got middle limit. ( i got the Ex-God limit ) And if i do in pex `- -mywarp.limit.ExGod` (and ExMaster/ExVip) Then i got the right limit (Legend) Or its it normale? i suppose not.

Mywarp config (limits)
```YAML
limits:
  enabled: true
  defaultLimit:
    totalLimit: 1
    publicLimit: 0
    privateLimit: 1
  configuredLimits:
    vip:
      totalLimit: 2
      publicLimit: 0
      privateLimit: 2
    Premium:
      totalLimit: 10
      publicLimit: 1
      privateLimit: 9
    master:
      totalLimit: 22
      publicLimit: 3
      privateLimit: 19
    god:
      totalLimit: 34
      publicLimit: 5
      privateLimit: 29
    Legend:
      totalLimit: 100
      publicLimit: 50
      privateLimit: 50
    ExMaster:
      totalLimit: 5
      publicLimit: 0
      privateLimit: 5
    ExGod:
      totalLimit: 11
      publicLimit: 1
      privateLimit: 10
```
